#!/usr/bin/env python3
"""
批量替换UI文件中的中文文本为英文
"""

import re
import os

def fix_ui_file():
    ui_file = "src/battery_analysis/ui/resources/ui_battery_analysis.ui"
    
    # 读取文件
    with open(ui_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 定义替换规则
    replacements = {
        "/* 绿色边框 */": "/* Green border */",
        "/* 圆角半径 */": "/* Border radius */",
        "/* 内边距，让文字不贴边 */": "/* Inner padding, prevent text from touching edges */",
        "/* 背景颜色 */": "/* Background color */",
        "/* 右侧预留给箭头 */": "/* Right padding reserved for arrow */",
        "/* 右侧按钮区去掉方框，只保留圆角过渡 */": "/* Remove frame from right button area, keep only corner transitions */",
        "/* 1) 外框圆角 */": "/* 1) Frame corner radius */",
        "/* 3) 指定自定义小三角 */": "/* 3) Specify custom small triangle */",
        "/* 让它别贴边，可按需调 */": "/* Prevent touching edge, adjust as needed */",
        "/* （可选）下拉展开时用向上三角 */": "/* (Optional) Use upward triangle when dropdown expands */",
        "/* 背景色 */": "/* Background color */",
        "/* 文本颜色 */": "/* Text color */",
        "/* 内边距，让内容不贴边 */": "/* Inner padding, prevent content from touching edges */",
        "/* 悬停效果 */": "/* Hover effect */",
        "/* 按下效果 */": "/* Press effect */",
        "<string>工具栏</string>": "<string>Toolbar</string>",
        "/* 现代蓝色 - 激活状态 */": "/* Modern blue - active state */",
        "/* 纯白背景 - 未激活状态 */": "/* Pure white background - inactive state */",
        "/* 深蓝色 - 悬停状态 */": "/* Dark blue - hover state */",
        "/* 更深蓝色 - 按下状态 */": "/* Darker blue - pressed state */",
        "/* 激活时白色文字 */": "/* White text when active */",
        "/* 未激活时深灰文字 */": "/* Dark gray text when inactive */",
        "/* 悬停时白色文字 */": "/* White text when hovering */",
        "/* 浅灰边框 */": "/* Light gray border */",
        "/* 减小字体以适应按钮 */": "/* Reduce font size to fit button */",
        "/* 中等字重 */": "/* Medium font weight */",
        "/* 内部边距 */": "/* Inner padding */",
        "/* 按钮间距 */": "/* Button spacing */",
        "/* 使用QtAgg后端，它会自动检测可用的Qt绑定（包括PyQt6） */": "/* Use QtAgg backend, which automatically detects available Qt bindings (including PyQt6) */",
        "/* 必须在导入pyplot之前设置后端 */": "/* Must set backend before importing pyplot */",
        "/* 配置matplotlib支持中文显示 */": "/* Configure matplotlib to support Chinese display */",
        "/* 解决负号显示问题 */": "/* Solve minus sign display problem */",
        "/* 现代化按钮样式配置 */": "/* Modern button style configuration */",
        "/* 按钮状态颜色 */": "/* Button state colors */",
        "/* 现代蓝色 - 激活状态 */": "/* Modern blue - active state */",
        "/* 纯白背景 - 未激活状态 */": "/* Pure white background - inactive state */",
        "/* 深蓝色 - 悬停状态 */": "/* Dark blue - hover state */",
        "/* 更深蓝色 - 按下状态 */": "/* Darker blue - pressed state */",
        "/* 文字颜色 */": "/* Text colors */",
        "/* 激活时白色文字 */": "/* White text when active */",
        "/* 未激活时深灰文字 */": "/* Dark gray text when inactive */",
        "/* 悬停时白色文字 */": "/* White text when hovering */",
        "/* 边框样式 */": "/* Border styles */",
        "/* 浅灰边框 */": "/* Light gray border */",
        "/* 圆角半径 */": "/* Corner radius */",
        "/* 阴影效果 */": "/* Shadow effects */",
        "/* 字体样式 */": "/* Font styles */",
        "/* 减小字体以适应按钮 */": "/* Reduce font size to fit button */",
        "/* 中等字重 */": "/* Medium font weight */",
        "/* 布局参数 */": "/* Layout parameters */",
        "/* 内部边距 */": "/* Inner padding */",
        "/* 按钮间距 */": "/* Button spacing */",
        "/* 开启Matplotlib的交互模式 */": "/* Enable matplotlib interactive mode */",
        "/* 配置日志 */": "/* Configure logging */",
        "/* 默认最大值 */": "/* Default maximum value */",
        "/* 默认没有电池数据 */": "/* Default no battery data */",
        "/* 数据加载状态标记 */": "/* Data loading status flag */",
        "/* 当前图表实例引用 */": "/* Current chart instance reference */",
        "/* 初始化坐标轴范围和刻度 */": "/* Initialize axis ranges and ticks */",
        "/* 使用配置的坐标轴范围 */": "/* Use configured axis range */",
        "/* X轴刻度值 */": "/* X-axis tick values */",
        "/* 先初始化默认数据结构 */": "/* Initialize default data structure first */",
        "/* 读取配置项 */": "/* Read configuration items */",
        "/* 如果提供了数据路径，覆盖配置文件中的路径 */": "/* If data path is provided, override the path in config file */",
        "/* 尝试查找其他可能的数据文件 */": "/* Try to find other possible data files */",
        "/* 默认不加载任何数据，只初始化基本参数 */": "/* Default not to load any data, only initialize basic parameters */",
        "/* 初始化时未提供数据路径，不加载数据 */": "/* No data path provided during initialization, not loading data */",
        "/* 语言切换处理 */": "/* Language switching handling */",
        "/* 更新图表标题 */": "/* Update chart title */",
        "/* 重新绘制图表以应用新的语言 */": "/* Redraw chart to apply new language */",
        "/* 尝试移除前后引号（如果存在） */": "/* Try to remove leading and trailing quotes (if exist) */",
        "/* 关闭当前图表 */": "/* Close current chart */",
        "/* 创建新图表 */": "/* Create new chart */",
        "/* 设置数据路径并更新CSV文件路径 */": "/* Set data path and update CSV file path */",
        "/* 更新后的CSV文件路径 */": "/* Updated CSV file path */",
        "/* 加载数据并处理，为绘制图表做准备 */": "/* Load and process data, prepare for chart drawing */",
        "/* 是否成功加载数据 */": "/* Whether data was loaded successfully */",
        "/* 检查是否有有效的电池数据，只有在有数据时才继续处理 */": "/* Check if there's valid battery data, only continue processing if there's data */",
        "/* 读取并处理规则配置 */": "/* Read and process rule configuration */",
        "/* 加载配置文件，优先使用setting.ini，其次是Config_BatteryAnalysis.ini */": "/* Load config file, prefer setting.ini, then Config_BatteryAnalysis.ini */",
        "/* 尝试从项目根目录的config文件夹读取配置文件，首先查找setting.ini， */": "/* Try to read config file from project root config folder, first look for setting.ini, */",
        "/* 如果不存在则尝试查找Config_BatteryAnalysis.ini。如果两个文件都不存在， */": "/* if not exist then try to find Config_BatteryAnalysis.ini. If both files don't exist, */",
        "/* 则使用默认配置并记录警告日志。 */": "/* use default configuration and record warning log. */",
        "/* 异常处理：捕获配置文件读取过程中可能出现的所有异常，并记录错误日志。 */": "/* Exception handling: catch all exceptions that may occur during config file reading, and record error log. */",
        "/* 优先读取setting.ini（发布模式） */": "/* Prefer reading setting.ini (release mode) */",
        "/* setting.ini存在时，不检查Config_BatteryAnalysis.ini */": "/* When setting.ini exists, don't check Config_BatteryAnalysis.ini */",
        "/* 如果setting.ini不存在，尝试查找Config_BatteryAnalysis.ini（兼容旧版本） */": "/* If setting.ini doesn't exist, try to find Config_BatteryAnalysis.ini (compatible with old version) */",
        "/* 未找到配置文件，使用默认配置 */": "/* Config file not found, use default configuration */",
        "/* 配置读取失败: %s，使用默认配置 */": "/* Config reading failed: %s, use default configuration */",
        "/* 读取所有配置项并设置默认值 */": "/* Read all configuration items and set default values */",
        "/* 从加载的配置文件中读取图表路径、标题、脉冲电流级别、电池规格类型等配置项， */": "/* Read chart path, title, pulse current level, battery specification type and other configuration items from the loaded config file, */",
        "/* 并为每个配置项设置合理的默认值。 */": "/* and set reasonable default values for each configuration item. */",
        "/* 配置项包括： */": "/* Configuration items include: */",
        "/* - 图表路径和标题 */": "/* - Chart path and title */",
        "/* - CSV文件路径 */": "/* - CSV file path */",
        "/* - 脉冲电流级别配置 */": "/* - Pulse current level configuration */",
        "/* - 电池规格类型配置（纽扣电池和软包电池） */": "/* - Battery specification type configuration (coin cell and pouch cell) */",
        "/* 读取图表路径配置 */": "/* Read chart path configuration */",
        "/* 读取图表标题配置 */": "/* Read chart title configuration */",
        "/* 设置CSV文件路径 */": "/* Set CSV file path */",
        "/* 读取脉冲电流级别配置 */": "/* Read pulse current level configuration */",
        "/* 读取电池规格类型配置 */": "/* Read battery specification type configuration */",
        "/* 设置图表标题 */": "/* Set chart title */",
        "/* 获取默认坐标轴范围 */": "/* Get default axis range */",
        "/* 默认坐标轴范围 [xmin, xmax, ymin, ymax] */": "/* Default axis range [xmin, xmax, ymin, ymax] */",
        "/* 设置默认坐标轴范围 */": "/* Set default axis range */",
        "/* X轴最小值 */": "/* X-axis minimum value */",
        "/* X轴最大值 */": "/* X-axis maximum value */",
        "/* Y轴最小值 */": "/* Y-axis minimum value */",
        "/* Y轴最大值 */": "/* Y-axis maximum value */",
        "/* 如果当前使用的是默认范围，同步更新当前listAxis */": "/* If currently using default range, sync update current listAxis */",
        "/* 获取特殊规则下的坐标轴范围 */": "/* Get axis range under special rules */",
        "/* 特殊规则下的坐标轴范围 [xmin, xmax, ymin, ymax] */": "/* Axis range under special rules [xmin, xmax, ymin, ymax] */",
        "/* 设置特殊规则下的坐标轴范围 */": "/* Set axis range under special rules */",
        "/* 获取整个图表配置对象 */": "/* Get entire chart configuration object */",
        "/* 图表配置对象 */": "/* Chart configuration object */",
        "/* 安全获取配置值，如果不存在则返回默认值 */": "/* Safely get config value, return default value if not exist */",
        "/* 从配置文件中读取指定section和option的值。如果section或option不存在， */": "/* Read the value of specified section and option from config file. If section or option doesn't exist, */",
        "/* 或者读取过程中出现异常，则返回提供的默认值并记录相应的日志信息。 */": "/* or exception occurs during reading, return the provided default value and record corresponding log info. */",
        "/* 配置文件中的section名称 */": "/* Section name in config file */",
        "/* 配置项名称 */": "/* Configuration item name */",
        "/* 默认值，当配置项不存在时返回 */": "/* Default value, returned when config item doesn't exist */",
        "/* 配置值或默认值 */": "/* Configuration value or default value */",
        "/* 安全获取配置列表，如果不存在则返回空列表 */": "/* Safely get config list, return empty list if not exist */",
        "/* 未找到配置列表 %s/%s，使用空列表 */": "/* Config list %s/%s not found, use empty list */",
        "/* 读取配置列表 %s/%s 出错: %s，使用空列表 */": "/* Error reading config list %s/%s: %s, use empty list */",
        "/* 获取脉冲电流级别配置 */": "/* Get pulse current level configuration */",
        "/* 使用配置的脉冲电流级别: %s */": "/* Use configured pulse current level: %s */",
        "/* 未找到BatteryConfig/PulseCurrent，使用默认值: %s */": "/* BatteryConfig/PulseCurrent not found, use default value: %s */",
        "/* 脉冲电流配置格式错误: %s，使用默认值: %s */": "/* Pulse current config format error: %s, use default value: %s */",
        "/* 设置图表标题，处理引号情况 */": "/* Set chart title, handle quote situation */",
        "/* 尝试移除前后引号（如果存在） */": "/* Try to remove leading and trailing quotes (if exist) */",
        "/* 设置图表标题出错: %s，使用默认标题: %s */": "/* Error setting chart title: %s, use default title: %s */",
        "/* 读取并处理规则配置 */": "/* Read and process rule configuration */",
        "/* 根据规则配置处理maxXaxis */": "/* Process maxXaxis according to rule configuration */",
        "/* 根据规则设置maxXaxis: %s */": "/* Set maxXaxis according to rules: %s */",
        "/* 同步更新坐标轴范围和刻度 */": "/* Sync update axis range and ticks */",
        "/* 规则中的maxXaxis值无效: %s */": "/* Invalid maxXaxis value in rule: %s */",
        "/* 处理规则时出错: %s，保持默认maxXaxis */": "/* Error processing rules: %s, keep default maxXaxis */",
        "/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */": "/* 2) Remove frame from right button area, keep only corner transitions */"
    }
    
    # 应用替换
    for chinese, english in replacements.items():
        content = content.replace(chinese, english)
    
    # 写入文件
    with open(ui_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"已修复UI文件中的中文文本: {ui_file}")

if __name__ == "__main__":
    fix_ui_file()