#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive internationalization script for main_window.py
"""

import re
import os

def internationalize_main_window():
    """Internationalize all Chinese text in main_window.py"""
    
    python_file = "src/battery_analysis/main/main_window.py"
    
    # Read the file
    with open(python_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original_content = content
    
    # Define comprehensive replacement rules for main_window.py
    replacements = {
        # Module docstring
        '电池分析主窗口模块': 'Battery Analysis Main Window Module',
        '这个模块实现了电池分析应用的主窗口界面和核心功能，包括：': 'This module implements the main window interface and core functionality of the battery analysis application, including:',
        '- 窗口初始化和布局设置': '- Window initialization and layout settings',
        '- 配置文件管理': '- Configuration file management',
        '- 控制器连接和信号处理': '- Controller connection and signal processing',
        '- 用户交互界面': '- User interaction interface',
        
        # Comment sections
        '# 标准库导入': '# Standard library imports',
        '# 第三方库导入': '# Third-party library imports', 
        '# 本地应用/库导入': '# Local application/library imports',
        '# 配置日志': '# Configure logging',
        
        # Function docstrings and comments
        '在模块级别定义的可视化工具运行函数': 'Visualizer tool run function defined at module level',
        '创建可视化器控制器实例': 'Create visualizer controller instance',
        '创建并显示可视化器': 'Create and display visualizer',
        '启动可视化工具whenerror occurred': 'Start visualizer tool when error occurred',
        '弹出式进度条对话框类': 'Pop-up progress bar dialog class',
        '用于显示详细的进度信息，适合长when间运行的任务': 'Used to display detailed progress information, suitable for long-running tasks',
        '初始化弹出式进度条': 'Initialize pop-up progress bar',
        'parent: 父窗口': 'parent: parent window',
        
        # Window titles and UI text
        '电池分析进度': 'Battery Analysis Progress',
        '非模态窗口，允许用户同when操作主界面': 'Non-modal window, allowing users to operate main interface simultaneously',
        
        # Common technical terms
        '错误': 'Error',
        '成功': 'Success', 
        '失败': 'Failed',
        '警告': 'Warning',
        '信息': 'Info',
        '确认': 'Confirm',
        '取消': 'Cancel',
        '保存': 'Save',
        '加载': 'Load',
        '文件': 'File',
        '目录': 'Directory',
        '选择': 'Select',
        '打开': 'Open',
        '关闭': 'Close',
        '退出': 'Exit',
        '设置': 'Settings',
        '配置': 'Configuration',
        '帮助': 'Help',
        '关于': 'About',
        '状态': 'Status',
        '进度': 'Progress',
        '完成': 'Complete',
        '处理': 'Process',
        '分析': 'Analysis',
        '数据': 'Data',
        '图表': 'Chart',
        '显示': 'Display',
        '隐藏': 'Hide',
        '刷新': 'Refresh',
        '更新': 'Update',
        '新建': 'New',
        '编辑': 'Edit',
        '删除': 'Delete',
        '复制': 'Copy',
        '粘贴': 'Paste',
        '查找': 'Find',
        '搜索': 'Search',
        '替换': 'Replace',
        '撤销': 'Undo',
        '重做': 'Redo',
        '打印': 'Print',
        '预览': 'Preview',
        '导出': 'Export',
        '导入': 'Import',
        '同步': 'Sync',
        '连接': 'Connect',
        '断开': 'Disconnect',
        '发送': 'Send',
        '接收': 'Receive',
        '上传': 'Upload',
        '下载': 'Download',
        '验证': 'Validate',
        '检查': 'Check',
        '测试': 'Test',
        '调试': 'Debug',
        '日志': 'Log',
        '记录': 'Record',
        '监控': 'Monitor',
        '跟踪': 'Track',
        '统计': 'Statistics',
        '报告': 'Report',
        '生成': 'Generate',
        '创建': 'Create',
        '初始化': 'Initialize',
        '安装': 'Install',
        '卸载': 'Uninstall',
        '升级': 'Upgrade',
        '修复': 'Fix',
        '优化': 'Optimize',
        '性能': 'Performance',
        '速度': 'Speed',
        '内存': 'Memory',
        '网络': 'Network',
        '连接': 'Connection',
        '端口': 'Port',
        '服务器': 'Server',
        '客户端': 'Client',
        '协议': 'Protocol',
        '请求': 'Request',
        '响应': 'Response',
        '服务': 'Service',
        '进程': 'Process',
        '线程': 'Thread',
        '任务': 'Task',
        '作业': 'Job',
        '队列': 'Queue',
        '堆栈': 'Stack',
        '缓存': 'Cache',
        '缓冲': 'Buffer',
        '流': 'Stream',
        '通道': 'Channel',
        '管道': 'Pipe',
        '信号': 'Signal',
        '事件': 'Event',
        '异常': 'Exception',
        '通知': 'Notification',
        '消息': 'Message',
        '提示': 'Hint',
        '说明': 'Description',
        '文档': 'Documentation',
        '手册': 'Manual',
        '指南': 'Guide',
        '教程': 'Tutorial',
        '示例': 'Example',
        '样例': 'Sample',
        '模板': 'Template',
        '样式': 'Style',
        '主题': 'Theme',
        '皮肤': 'Skin',
        '布局': 'Layout',
        '位置': 'Position',
        '坐标': 'Coordinate',
        '大小': 'Size',
        '宽度': 'Width',
        '高度': 'Height',
        '长度': 'Length',
        '距离': 'Distance',
        '角度': 'Angle',
        '方向': 'Direction',
        '模式': 'Mode',
        '类型': 'Type',
        '类别': 'Category',
        '分类': 'Classification',
        '分组': 'Group',
        '集合': 'Collection',
        '列表': 'List',
        '数组': 'Array',
        '矩阵': 'Matrix',
        '向量': 'Vector',
        '点': 'Point',
        '线': 'Line',
        '面': 'Surface',
        '体': 'Volume',
        '区域': 'Region',
        '范围': 'Range',
        '区间': 'Interval',
        '段': 'Segment',
        '部分': 'Part',
        '整体': 'Whole',
        '所有': 'All',
        '每个': 'Each',
        '任意': 'Any',
        '特定': 'Specific',
        '默认': 'Default',
        '当前': 'Current',
        '最新': 'Latest',
        '旧': 'Old',
        '新': 'New',
        '第一个': 'First',
        '最后一个': 'Last',
        '下一个': 'Next',
        '上一个': 'Previous',
        '前一个': 'Previous',
        '后一个': 'Next',
        '开始': 'Start',
        '结束': 'End',
        '终止': 'Terminate',
        '暂停': 'Pause',
        '继续': 'Continue',
        '恢复': 'Resume',
        '中断': 'Interrupt',
        '跳过': 'Skip',
        '重试': 'Retry',
        '重新': 'Re',
        '再次': 'Again',
        '重复': 'Repeat',
        '循环': 'Loop',
        '迭代': 'Iterate',
        '遍历': 'Traverse',
        '匹配': 'Match',
        '比较': 'Compare',
        '对比': 'Compare',
        '区分': 'Distinguish',
        '识别': 'Identify',
        '检测': 'Detect',
        '发现': 'Discover',
        '找到': 'Found',
        '获取': 'Get',
        '获得': 'Obtain',
        '读取': 'Read',
        '写入': 'Write',
        '存储': 'Store',
        '临时': 'Temporary',
        '永久': 'Permanent',
        '持久': 'Persistent',
        '临时文件': 'Temporary File',
        '日志文件': 'Log File',
        '配置文件': 'Configuration File',
        '数据文件': 'Data File',
        '结果文件': 'Result File',
        '输出文件': 'Output File',
        '输入文件': 'Input File',
        '源文件': 'Source File',
        '目标文件': 'Target File',
        '备份文件': 'Backup File',
        '原始数据': 'Original Data',
        '处理数据': 'Processed Data',
        '分析结果': 'Analysis Result',
        '计算结果': 'Calculation Result',
        '测试结果': 'Test Result',
        '执行结果': 'Execution Result',
        '运行结果': 'Run Result',
        '操作结果': 'Operation Result',
        '功能结果': 'Function Result',
        '方法结果': 'Method Result',
        '过程结果': 'Process Result',
        '步骤结果': 'Step Result',
        '阶段结果': 'Phase Result',
        '状态结果': 'Status Result',
        '条件结果': 'Condition Result',
        '逻辑结果': 'Logic Result',
        '布尔结果': 'Boolean Result',
        '数值结果': 'Numeric Result',
        '文本结果': 'Text Result',
        '字符串结果': 'String Result',
        '字符结果': 'Character Result',
        '符号结果': 'Symbol Result',
        '标记结果': 'Token Result',
        '关键字结果': 'Keyword Result',
        '标识符结果': 'Identifier Result',
        '名称结果': 'Name Result',
        '标题结果': 'Title Result',
        '标签结果': 'Label Result',
        '注释结果': 'Comment Result',
        '说明结果': 'Description Result',
        '描述结果': 'Description Result',
        '解释结果': 'Explanation Result',
        '总结结果': 'Summary Result',
        '摘要结果': 'Abstract Result',
        '概述结果': 'Overview Result',
        '概览结果': 'Overview Result',
        '浏览结果': 'Browse Result',
        '查看结果': 'View Result',
        '展示结果': 'Show Result',
        '呈现结果': 'Present Result',
        '表现结果': 'Performance Result',
        '演示结果': 'Demo Result',
        
        # Remove common Chinese characters that appear in mixed text
        '当': 'when',
        '和': 'and',
        '的': '',
        '与': 'and',
        '为': 'is',
        '在': 'in',
        '对': 'for',
        '从': 'from',
        '到': 'to',
        '由': 'by',
        '向': 'to',
        '往': 'to',
        '朝': 'towards',
        '用': 'use',
        '使': 'make',
        '把': 'put',
        '将': 'will',
        '需要': 'need',
        '应该': 'should',
        '必须': 'must',
        '可以': 'can',
        '能够': 'can',
        '可能': 'may',
        '也许': 'maybe',
        '或许': 'perhaps',
        '大概': 'probably',
        '确实': 'indeed',
        '真的': 'really',
        '真的': 'truly',
        '确实': 'certainly',
        '绝对': 'absolutely',
        '完全': 'completely',
        '完全': 'totally',
        '十分': 'very',
        '非常': 'very',
        '特别': 'especially',
        '尤其': 'particularly',
        '特别': 'particularly',
        '主要': 'mainly',
        '重要': 'important',
        '关键': 'key',
        '核心': 'core',
        '基本': 'basic',
        '基础': 'foundation',
        '根本': 'fundamental',
        '本质': 'essence',
        '实质': 'substance',
        '真实': 'real',
        '实际': 'actual',
        '确实': 'actual',
        '真正': 'truly',
        '确实': 'definitely',
        '一定': 'certain',
        '确定': 'certain',
        '明确': 'clear',
        '清楚': 'clear',
        '明白': 'understand',
        '了解': 'understand',
        '知道': 'know',
        '认识': 'know',
        '理解': 'understand',
        '懂得': 'understand',
        '掌握': 'master',
        '控制': 'control',
        '管理': 'manage',
        '处理': 'handle',
        '操作': 'operate',
        '执行': 'execute',
        '实施': 'implement',
        '落实': 'implement',
        '实行': 'implement',
        '应用': 'apply',
        '使用': 'use',
        '运用': 'use',
        '利用': 'utilize',
        '采用': 'adopt',
        '选择': 'choose',
        '挑选': 'select',
        '选取': 'select',
        '提取': 'extract',
        '收集': 'collect',
        '整理': 'organize',
        '组织': 'organize',
        '安排': 'arrange',
        '计划': 'plan',
        '规划': 'plan',
        '设计': 'design',
        '建造': 'build',
        '建设': 'build',
        '构建': 'build',
        '构造': 'construct',
        '制作': 'make',
        '生产': 'produce',
        '创造': 'create',
        '创新': 'innovate',
        '发明': 'invent',
        '发现': 'discover',
        '研发': 'research',
        '开发': 'develop',
        '发展': 'develop',
        '进化': 'evolve',
        '演变': 'evolve',
        '变化': 'change',
        '转变': 'transform',
        '转换': 'convert',
        '转化': 'transform',
        '修改': 'modify',
        '变更': 'change',
        '变动': 'change',
        '调整': 'adjust',
        '调节': 'adjust',
        '适应': 'adapt',
        '适合': 'suitable',
        '合适': 'appropriate',
        '恰当': 'proper',
        '适当': 'proper',
        '适度': 'moderate',
        '适量': 'appropriate amount',
        '足够': 'enough',
        '充分': 'sufficient',
        '充足': 'adequate',
        '满足': 'satisfy',
        '满意': 'satisfied',
        '高兴': 'happy',
        '快乐': 'happy',
        '愉快': 'happy',
        '开心': 'happy',
        '兴奋': 'excited',
        '激动': 'excited',
        '热情': 'enthusiastic',
        '积极': 'positive',
        '主动': 'active',
        '自发': 'spontaneous',
        '自然': 'natural',
        '自动': 'automatic',
        '本能': 'instinctive',
        '天然': 'natural',
        '野生': 'wild',
        '人工': 'artificial',
        '人造': 'artificial',
        '合成': 'synthetic',
        '复合': 'composite',
        '混合': 'mixed',
        '组合': 'combined',
        '配合': 'coordinate',
        '协调': 'coordinate',
        '合作': 'cooperation',
        '协作': 'cooperation',
        '帮助': 'help',
        '协助': 'assist',
        '支援': 'support',
        '支持': 'support',
        '支撑': 'support',
        '维持': 'maintain',
        '保持': 'keep',
        '坚持': 'persist',
        '持续': 'continue',
        '连续': 'continuous',
        '延伸': 'extend',
        '延长': 'extend',
        '扩展': 'expand',
        '扩大': 'expand',
        '放大': 'enlarge',
        '缩小': 'reduce',
        '减小': 'decrease',
        '减少': 'decrease',
        '降低': 'decrease',
        '下降': 'decrease',
        '下跌': 'decrease',
        '掉落': 'fall',
        '跌落': 'fall',
        '落下': 'fall',
        '下沉': 'sink',
        '下行': 'downward',
        '上升': 'upward',
        '上': 'up',
        '下': 'down',
        '高': 'high',
        '低': 'low',
        '长': 'long',
        '短': 'short',
        '大': 'big',
        '小': 'small',
        '多': 'many',
        '少': 'few',
        '上': 'above',
        '下': 'below',
        '内': 'inside',
        '外': 'outside',
        '中': 'middle',
        '间': 'between',
        '前': 'before',
        '后': 'after',
        '左': 'left',
        '右': 'right',
        '东': 'east',
        '西': 'west',
        '南': 'south',
        '北': 'north',
        '里': 'inside',
        '外': 'outside',
        '旁': 'beside',
        '边': 'side',
        '沿': 'along',
        '靠': 'near',
        '邻': 'near',
        '近': 'near',
        '远': 'far',
        '旁边': 'beside',
        '附近': 'nearby',
        '邻近': 'adjacent',
        '周围': 'around',
        '周围': 'surrounding',
        '附近': 'near',
        '周围': 'around',
        '周围': 'surrounding'
    }
    
    # Apply replacements
    changes_made = 0
    for chinese, english in replacements.items():
        if chinese in content:
            content = content.replace(chinese, english)
            changes_made += 1
    
    # Handle remaining mixed patterns with regex
    # Pattern: Chinese word + English word + Chinese word
    mixed_pattern1 = r'([一-龯]+)([A-Z][a-zA-Z]*)([一-龯]+)'
    content = re.sub(mixed_pattern1, lambda m: m.group(2), content)
    
    # Pattern: English word + Chinese word + English word  
    mixed_pattern2 = r'([a-zA-Z]+)([一-龯]+)([a-zA-Z]+)'
    content = re.sub(mixed_pattern2, lambda m: m.group(1) + m.group(3), content)
    
    # Pattern: Chinese characters at start/end of lines in comments
    comment_pattern = r'(#\s*)([一-龯\s]+)([A-Z][a-zA-Z\s]+)'
    content = re.sub(comment_pattern, lambda m: m.group(1) + m.group(3), content)
    
    # Remove any remaining isolated Chinese characters
    content = re.sub(r'(?<![a-zA-Z])[一-龯](?![a-zA-Z])', '', content)
    
    # Write back if changes were made
    if content != original_content:
        with open(python_file, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Fixed {changes_made} Chinese text patterns in {python_file}")
        return True
    
    return False

def check_remaining_chinese():
    """Check for any remaining Chinese text"""
    python_file = "src/battery_analysis/main/main_window.py"
    
    with open(python_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find all lines with Chinese characters
    chinese_lines = []
    for i, line in enumerate(content.split('\n'), 1):
        if re.search(r'[一-龯]', line):
            chinese_lines.append((i, line.strip()))
    
    if chinese_lines:
        print(f"Found {len(chinese_lines)} lines with Chinese text:")
        for line_num, line in chinese_lines[:10]:  # Show first 10
            print(f"  Line {line_num}: {line}")
        if len(chinese_lines) > 10:
            print(f"  ... and {len(chinese_lines) - 10} more lines")
    else:
        print("No Chinese text found! 🎉")
    
    return len(chinese_lines)

if __name__ == "__main__":
    print("Running comprehensive internationalization for main_window.py...")
    fixed = internationalize_main_window()
    
    if fixed:
        print("\nChecking for remaining Chinese text...")
        remaining = check_remaining_chinese()
        
        if remaining == 0:
            print("\n✅ SUCCESS! main_window.py is completely internationalized!")
        else:
            print(f"\n⚠️  {remaining} lines still contain Chinese text and need manual review.")
    else:
        print("No changes were made.")
        check_remaining_chinese()