# Form implementation generated from reading ui file './src/battery_analysis/ui/resources/ui_battery_analysis.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 885)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_BatteryConfig = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_BatteryConfig.setGeometry(QtCore.QRect(10, 235, 731, 351))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.groupBox_BatteryConfig.setFont(font)
        self.groupBox_BatteryConfig.setObjectName("groupBox_BatteryConfig")
        self.frame = QtWidgets.QFrame(parent=self.groupBox_BatteryConfig)
        self.frame.setGeometry(QtCore.QRect(380, 200, 341, 140))
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 341, 97))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_Temperature = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Temperature.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_Temperature.setObjectName("horizontalLayout_Temperature")
        self.label_Temperature = QtWidgets.QLabel(parent=self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Temperature.sizePolicy().hasHeightForWidth())
        self.label_Temperature.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_Temperature.setFont(font)
        self.label_Temperature.setObjectName("label_Temperature")
        self.horizontalLayout_Temperature.addWidget(self.label_Temperature)
        spacerItem = QtWidgets.QSpacerItem(53, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Temperature.addItem(spacerItem)
        self.lineEdit_Temperature = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Temperature.sizePolicy().hasHeightForWidth())
        self.lineEdit_Temperature.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_Temperature.setFont(font)
        self.lineEdit_Temperature.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_Temperature.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_Temperature.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.lineEdit_Temperature.setAutoFillBackground(False)
        self.lineEdit_Temperature.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_Temperature.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_Temperature.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_Temperature.setReadOnly(False)
        self.lineEdit_Temperature.setObjectName("lineEdit_Temperature")
        self.horizontalLayout_Temperature.addWidget(self.lineEdit_Temperature)
        self.verticalLayout_8.addLayout(self.horizontalLayout_Temperature)
        self.horizontalLayout_AcceleratedAging = QtWidgets.QHBoxLayout()
        self.horizontalLayout_AcceleratedAging.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_AcceleratedAging.setObjectName("horizontalLayout_AcceleratedAging")
        self.label_AcceleratedAging = QtWidgets.QLabel(parent=self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_AcceleratedAging.sizePolicy().hasHeightForWidth())
        self.label_AcceleratedAging.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_AcceleratedAging.setFont(font)
        self.label_AcceleratedAging.setObjectName("label_AcceleratedAging")
        self.horizontalLayout_AcceleratedAging.addWidget(self.label_AcceleratedAging)
        spacerItem1 = QtWidgets.QSpacerItem(4, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_AcceleratedAging.addItem(spacerItem1)
        self.spinBox_AcceleratedAging = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_AcceleratedAging.sizePolicy().hasHeightForWidth())
        self.spinBox_AcceleratedAging.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.spinBox_AcceleratedAging.setFont(font)
        self.spinBox_AcceleratedAging.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.spinBox_AcceleratedAging.setStyleSheet("")
        self.spinBox_AcceleratedAging.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBox_AcceleratedAging.setMinimum(0)
        self.spinBox_AcceleratedAging.setMaximum(10)
        self.spinBox_AcceleratedAging.setProperty("value", 0)
        self.spinBox_AcceleratedAging.setObjectName("spinBox_AcceleratedAging")
        self.horizontalLayout_AcceleratedAging.addWidget(self.spinBox_AcceleratedAging)
        self.verticalLayout_8.addLayout(self.horizontalLayout_AcceleratedAging)
        self.frame_2 = QtWidgets.QFrame(parent=self.groupBox_BatteryConfig)
        self.frame_2.setGeometry(QtCore.QRect(380, 20, 341, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 341, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_Manufacturer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Manufacturer.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_Manufacturer.setObjectName("horizontalLayout_Manufacturer")
        self.label_Manufacturer = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Manufacturer.sizePolicy().hasHeightForWidth())
        self.label_Manufacturer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_Manufacturer.setFont(font)
        self.label_Manufacturer.setObjectName("label_Manufacturer")
        self.horizontalLayout_Manufacturer.addWidget(self.label_Manufacturer)
        spacerItem2 = QtWidgets.QSpacerItem(25, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Manufacturer.addItem(spacerItem2)
        self.comboBox_Manufacturer = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.comboBox_Manufacturer.setFont(font)
        self.comboBox_Manufacturer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_Manufacturer.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox_Manufacturer.setStyleSheet("/* 1) 外框圆角 */\n"
"QComboBox {\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 6px;\n"
"    padding: 2px 28px 2px 8px;   /* 右侧预留给箭头 */\n"
"    background: #F6F6F6;\n"
"}\n"
"\n"
"/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"/* 3) 指定自定义小三角 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right: 4px; /* 让它别贴边，可按需调 */\n"
"}\n"
"\n"
"/* （可选）下拉展开时用向上三角 */\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/chevron-up.svg);\n"
"}\n"
"")
        self.comboBox_Manufacturer.setEditable(False)
        self.comboBox_Manufacturer.setObjectName("comboBox_Manufacturer")
        self.horizontalLayout_Manufacturer.addWidget(self.comboBox_Manufacturer)
        self.verticalLayout_5.addLayout(self.horizontalLayout_Manufacturer)
        self.horizontalLayout_BatchDateCode = QtWidgets.QHBoxLayout()
        self.horizontalLayout_BatchDateCode.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_BatchDateCode.setObjectName("horizontalLayout_BatchDateCode")
        self.label_BatchDateCode = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_BatchDateCode.sizePolicy().hasHeightForWidth())
        self.label_BatchDateCode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_BatchDateCode.setFont(font)
        self.label_BatchDateCode.setObjectName("label_BatchDateCode")
        self.horizontalLayout_BatchDateCode.addWidget(self.label_BatchDateCode)
        spacerItem3 = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_BatchDateCode.addItem(spacerItem3)
        self.lineEdit_BatchDateCode = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_BatchDateCode.setFont(font)
        self.lineEdit_BatchDateCode.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_BatchDateCode.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_BatchDateCode.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_BatchDateCode.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_BatchDateCode.setObjectName("lineEdit_BatchDateCode")
        self.horizontalLayout_BatchDateCode.addWidget(self.lineEdit_BatchDateCode)
        self.verticalLayout_5.addLayout(self.horizontalLayout_BatchDateCode)
        self.horizontalLayout_SamplesQty = QtWidgets.QHBoxLayout()
        self.horizontalLayout_SamplesQty.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_SamplesQty.setObjectName("horizontalLayout_SamplesQty")
        self.label_SamplesQty = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SamplesQty.sizePolicy().hasHeightForWidth())
        self.label_SamplesQty.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_SamplesQty.setFont(font)
        self.label_SamplesQty.setObjectName("label_SamplesQty")
        self.horizontalLayout_SamplesQty.addWidget(self.label_SamplesQty)
        spacerItem4 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_SamplesQty.addItem(spacerItem4)
        self.lineEdit_SamplesQty = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_SamplesQty.setFont(font)
        self.lineEdit_SamplesQty.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_SamplesQty.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_SamplesQty.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_SamplesQty.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_SamplesQty.setObjectName("lineEdit_SamplesQty")
        self.horizontalLayout_SamplesQty.addWidget(self.lineEdit_SamplesQty)
        self.verticalLayout_5.addLayout(self.horizontalLayout_SamplesQty)
        self.frame_3 = QtWidgets.QFrame(parent=self.groupBox_BatteryConfig)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 361, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.frame_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 361, 181))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_BatteryType = QtWidgets.QHBoxLayout()
        self.horizontalLayout_BatteryType.setContentsMargins(5, 5, 10, 5)
        self.horizontalLayout_BatteryType.setObjectName("horizontalLayout_BatteryType")
        self.label_BatteryType = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_BatteryType.sizePolicy().hasHeightForWidth())
        self.label_BatteryType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_BatteryType.setFont(font)
        self.label_BatteryType.setObjectName("label_BatteryType")
        self.horizontalLayout_BatteryType.addWidget(self.label_BatteryType)
        spacerItem5 = QtWidgets.QSpacerItem(62, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_BatteryType.addItem(spacerItem5)
        self.comboBox_BatteryType = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_4)
        self.comboBox_BatteryType.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_BatteryType.sizePolicy().hasHeightForWidth())
        self.comboBox_BatteryType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.comboBox_BatteryType.setFont(font)
        self.comboBox_BatteryType.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_BatteryType.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox_BatteryType.setStyleSheet("/* 1) 外框圆角 */\n"
"QComboBox {\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 6px;\n"
"    padding: 2px 28px 2px 8px;   /* 右侧预留给箭头 */\n"
"    background: #F6F6F6;\n"
"}\n"
"\n"
"/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"/* 3) 指定自定义小三角 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right: 4px; /* 让它别贴边，可按需调 */\n"
"}\n"
"\n"
"/* （可选）下拉展开时用向上三角 */\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/chevron-up.svg);\n"
"}\n"
"")
        self.comboBox_BatteryType.setEditable(False)
        self.comboBox_BatteryType.setObjectName("comboBox_BatteryType")
        self.horizontalLayout_BatteryType.addWidget(self.comboBox_BatteryType)
        self.verticalLayout_7.addLayout(self.horizontalLayout_BatteryType)
        self.horizontalLayout_ConstructionMethod = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ConstructionMethod.setContentsMargins(5, 5, 10, 5)
        self.horizontalLayout_ConstructionMethod.setObjectName("horizontalLayout_ConstructionMethod")
        self.label_ConstructionMethod = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ConstructionMethod.sizePolicy().hasHeightForWidth())
        self.label_ConstructionMethod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_ConstructionMethod.setFont(font)
        self.label_ConstructionMethod.setObjectName("label_ConstructionMethod")
        self.horizontalLayout_ConstructionMethod.addWidget(self.label_ConstructionMethod)
        spacerItem6 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_ConstructionMethod.addItem(spacerItem6)
        self.comboBox_ConstructionMethod = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ConstructionMethod.sizePolicy().hasHeightForWidth())
        self.comboBox_ConstructionMethod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.comboBox_ConstructionMethod.setFont(font)
        self.comboBox_ConstructionMethod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_ConstructionMethod.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox_ConstructionMethod.setStyleSheet("/* 1) 外框圆角 */\n"
"QComboBox {\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 6px;\n"
"    padding: 2px 28px 2px 8px;   /* 右侧预留给箭头 */\n"
"    background: #F6F6F6;\n"
"}\n"
"\n"
"/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"/* 3) 指定自定义小三角 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right: 4px; /* 让它别贴边，可按需调 */\n"
"}\n"
"\n"
"/* （可选）下拉展开时用向上三角 */\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/chevron-up.svg);\n"
"}\n"
"")
        self.comboBox_ConstructionMethod.setEditable(False)
        self.comboBox_ConstructionMethod.setObjectName("comboBox_ConstructionMethod")
        self.horizontalLayout_ConstructionMethod.addWidget(self.comboBox_ConstructionMethod)
        self.verticalLayout_7.addLayout(self.horizontalLayout_ConstructionMethod)
        self.horizontalLayout_Specification = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Specification.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_Specification.setObjectName("horizontalLayout_Specification")
        self.label_Specification = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Specification.sizePolicy().hasHeightForWidth())
        self.label_Specification.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_Specification.setFont(font)
        self.label_Specification.setObjectName("label_Specification")
        self.horizontalLayout_Specification.addWidget(self.label_Specification)
        spacerItem7 = QtWidgets.QSpacerItem(45, 75, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Specification.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_Specification_Method = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Specification_Method.sizePolicy().hasHeightForWidth())
        self.comboBox_Specification_Method.setSizePolicy(sizePolicy)
        self.comboBox_Specification_Method.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.comboBox_Specification_Method.setFont(font)
        self.comboBox_Specification_Method.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_Specification_Method.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox_Specification_Method.setStyleSheet("/* 1) 外框圆角 */\n"
"QComboBox {\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 6px;\n"
"    padding: 2px 28px 2px 8px;   /* 右侧预留给箭头 */\n"
"    background: #F6F6F6;\n"
"}\n"
"\n"
"/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"/* 3) 指定自定义小三角 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right: 4px; /* 让它别贴边，可按需调 */\n"
"}\n"
"\n"
"/* （可选）下拉展开时用向上三角 */\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/chevron-up.svg);\n"
"}\n"
"")
        self.comboBox_Specification_Method.setEditable(False)
        self.comboBox_Specification_Method.setObjectName("comboBox_Specification_Method")
        self.verticalLayout_4.addWidget(self.comboBox_Specification_Method)
        self.comboBox_Specification_Type = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Specification_Type.sizePolicy().hasHeightForWidth())
        self.comboBox_Specification_Type.setSizePolicy(sizePolicy)
        self.comboBox_Specification_Type.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.comboBox_Specification_Type.setFont(font)
        self.comboBox_Specification_Type.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_Specification_Type.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox_Specification_Type.setStyleSheet("/* 1) 外框圆角 */\n"
"QComboBox {\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 6px;\n"
"    padding: 2px 28px 2px 8px;   /* 右侧预留给箭头 */\n"
"    background: #F6F6F6;\n"
"}\n"
"\n"
"/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"/* 3) 指定自定义小三角 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right: 4px; /* 让它别贴边，可按需调 */\n"
"}\n"
"\n"
"/* （可选）下拉展开时用向上三角 */\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/chevron-up.svg);\n"
"}\n"
"")
        self.comboBox_Specification_Type.setEditable(False)
        self.comboBox_Specification_Type.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.comboBox_Specification_Type.setObjectName("comboBox_Specification_Type")
        self.verticalLayout_4.addWidget(self.comboBox_Specification_Type)
        self.horizontalLayout_Specification.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_Specification)
        self.frame_4 = QtWidgets.QFrame(parent=self.groupBox_BatteryConfig)
        self.frame_4.setGeometry(QtCore.QRect(10, 180, 361, 161))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(parent=self.frame_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 361, 148))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_9.setContentsMargins(5, 5, 10, 5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_RequiredUseableCapacity = QtWidgets.QHBoxLayout()
        self.horizontalLayout_RequiredUseableCapacity.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_RequiredUseableCapacity.setObjectName("horizontalLayout_RequiredUseableCapacity")
        self.label_RequiredUseableCapacity = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_RequiredUseableCapacity.sizePolicy().hasHeightForWidth())
        self.label_RequiredUseableCapacity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_RequiredUseableCapacity.setFont(font)
        self.label_RequiredUseableCapacity.setObjectName("label_RequiredUseableCapacity")
        self.horizontalLayout_RequiredUseableCapacity.addWidget(self.label_RequiredUseableCapacity)
        spacerItem8 = QtWidgets.QSpacerItem(25, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_RequiredUseableCapacity.addItem(spacerItem8)
        self.lineEdit_RequiredUseableCapacity = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_RequiredUseableCapacity.setFont(font)
        self.lineEdit_RequiredUseableCapacity.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_RequiredUseableCapacity.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_RequiredUseableCapacity.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_RequiredUseableCapacity.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_RequiredUseableCapacity.setObjectName("lineEdit_RequiredUseableCapacity")
        self.horizontalLayout_RequiredUseableCapacity.addWidget(self.lineEdit_RequiredUseableCapacity)
        self.verticalLayout_9.addLayout(self.horizontalLayout_RequiredUseableCapacity)
        self.horizontalLayout_CalculationNominalCapacity = QtWidgets.QHBoxLayout()
        self.horizontalLayout_CalculationNominalCapacity.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_CalculationNominalCapacity.setObjectName("horizontalLayout_CalculationNominalCapacity")
        self.label_CalculationNominalCapacity = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_CalculationNominalCapacity.setFont(font)
        self.label_CalculationNominalCapacity.setObjectName("label_CalculationNominalCapacity")
        self.horizontalLayout_CalculationNominalCapacity.addWidget(self.label_CalculationNominalCapacity)
        spacerItem9 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_CalculationNominalCapacity.addItem(spacerItem9)
        self.lineEdit_CalculationNominalCapacity = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_CalculationNominalCapacity.setFont(font)
        self.lineEdit_CalculationNominalCapacity.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_CalculationNominalCapacity.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_CalculationNominalCapacity.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_CalculationNominalCapacity.setObjectName("lineEdit_CalculationNominalCapacity")
        self.horizontalLayout_CalculationNominalCapacity.addWidget(self.lineEdit_CalculationNominalCapacity)
        self.verticalLayout_9.addLayout(self.horizontalLayout_CalculationNominalCapacity)
        self.horizontalLayout_DatasheetNominalCapacity = QtWidgets.QHBoxLayout()
        self.horizontalLayout_DatasheetNominalCapacity.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_DatasheetNominalCapacity.setObjectName("horizontalLayout_DatasheetNominalCapacity")
        self.label_DatasheetNominalCapacity = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DatasheetNominalCapacity.sizePolicy().hasHeightForWidth())
        self.label_DatasheetNominalCapacity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_DatasheetNominalCapacity.setFont(font)
        self.label_DatasheetNominalCapacity.setObjectName("label_DatasheetNominalCapacity")
        self.horizontalLayout_DatasheetNominalCapacity.addWidget(self.label_DatasheetNominalCapacity)
        spacerItem10 = QtWidgets.QSpacerItem(15, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_DatasheetNominalCapacity.addItem(spacerItem10)
        self.lineEdit_DatasheetNominalCapacity = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_DatasheetNominalCapacity.setFont(font)
        self.lineEdit_DatasheetNominalCapacity.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_DatasheetNominalCapacity.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_DatasheetNominalCapacity.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_DatasheetNominalCapacity.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_DatasheetNominalCapacity.setObjectName("lineEdit_DatasheetNominalCapacity")
        self.horizontalLayout_DatasheetNominalCapacity.addWidget(self.lineEdit_DatasheetNominalCapacity)
        self.verticalLayout_9.addLayout(self.horizontalLayout_DatasheetNominalCapacity)
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.groupBox_TestConfig = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_TestConfig.setGeometry(QtCore.QRect(10, 5, 730, 110))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.groupBox_TestConfig.setFont(font)
        self.groupBox_TestConfig.setStyleSheet("QGroupBox::groupBox_TestConfig {\n"
"    font: bold 14pt \"Arial\";\n"
"    color: #FF17365D;\n"
"    background-color: transparent;\n"
"}")
        self.groupBox_TestConfig.setObjectName("groupBox_TestConfig")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(parent=self.groupBox_TestConfig)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 60, 711, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.horizontalLayoutWidget_8.setFont(font)
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_TestProfile = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_TestProfile.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_TestProfile.setObjectName("horizontalLayout_TestProfile")
        self.label_TestProfile = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_TestProfile.sizePolicy().hasHeightForWidth())
        self.label_TestProfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_TestProfile.setFont(font)
        self.label_TestProfile.setObjectName("label_TestProfile")
        self.horizontalLayout_TestProfile.addWidget(self.label_TestProfile)
        spacerItem11 = QtWidgets.QSpacerItem(33, 0, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_TestProfile.addItem(spacerItem11)
        self.lineEdit_TestProfile = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_TestProfile.sizePolicy().hasHeightForWidth())
        self.lineEdit_TestProfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.lineEdit_TestProfile.setFont(font)
        self.lineEdit_TestProfile.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_TestProfile.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lineEdit_TestProfile.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_TestProfile.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_TestProfile.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_TestProfile.setReadOnly(True)
        self.lineEdit_TestProfile.setObjectName("lineEdit_TestProfile")
        self.horizontalLayout_TestProfile.addWidget(self.lineEdit_TestProfile)
        self.pushButton_TestProfile = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestProfile.sizePolicy().hasHeightForWidth())
        self.pushButton_TestProfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.pushButton_TestProfile.setFont(font)
        self.pushButton_TestProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_TestProfile.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_TestProfile.setObjectName("pushButton_TestProfile")
        self.horizontalLayout_TestProfile.addWidget(self.pushButton_TestProfile)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(parent=self.groupBox_TestConfig)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(480, 20, 241, 37))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.horizontalLayoutWidget_10.setFont(font)
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_TestedBy = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_TestedBy.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_TestedBy.setObjectName("horizontalLayout_TestedBy")
        self.label_TestedBy = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_TestedBy.sizePolicy().hasHeightForWidth())
        self.label_TestedBy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_TestedBy.setFont(font)
        self.label_TestedBy.setObjectName("label_TestedBy")
        self.horizontalLayout_TestedBy.addWidget(self.label_TestedBy)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_TestedBy.addItem(spacerItem12)
        self.comboBox_TestedBy = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.comboBox_TestedBy.setFont(font)
        self.comboBox_TestedBy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_TestedBy.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox_TestedBy.setStyleSheet("/* 1) 外框圆角 */\n"
"QComboBox {\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 6px;\n"
"    padding: 2px 28px 2px 8px;   /* 右侧预留给箭头 */\n"
"    background: #F6F6F6;\n"
"}\n"
"\n"
"/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"/* 3) 指定自定义小三角 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right: 4px; /* 让它别贴边，可按需调 */\n"
"}\n"
"\n"
"/* （可选）下拉展开时用向上三角 */\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/chevron-up.svg);\n"
"}\n"
"")
        self.comboBox_TestedBy.setEditable(False)
        self.comboBox_TestedBy.setObjectName("comboBox_TestedBy")
        self.horizontalLayout_TestedBy.addWidget(self.comboBox_TestedBy)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(parent=self.groupBox_TestConfig)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 441, 37))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.horizontalLayoutWidget_9.setFont(font)
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_TesterLocation = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_TesterLocation.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_TesterLocation.setObjectName("horizontalLayout_TesterLocation")
        self.label_TesterLocation = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_TesterLocation.sizePolicy().hasHeightForWidth())
        self.label_TesterLocation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_TesterLocation.setFont(font)
        self.label_TesterLocation.setObjectName("label_TesterLocation")
        self.horizontalLayout_TesterLocation.addWidget(self.label_TesterLocation)
        spacerItem13 = QtWidgets.QSpacerItem(5, 0, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_TesterLocation.addItem(spacerItem13)
        self.comboBox_TesterLocation = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_TesterLocation.sizePolicy().hasHeightForWidth())
        self.comboBox_TesterLocation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.comboBox_TesterLocation.setFont(font)
        self.comboBox_TesterLocation.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_TesterLocation.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox_TesterLocation.setStyleSheet("/* 1) 外框圆角 */\n"
"QComboBox {\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 6px;\n"
"    padding: 2px 28px 2px 8px;   /* 右侧预留给箭头 */\n"
"    background: #F6F6F6;\n"
"}\n"
"\n"
"/* 2) 右侧按钮区去掉方框，只保留圆角过渡 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"/* 3) 指定自定义小三角 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right: 4px; /* 让它别贴边，可按需调 */\n"
"}\n"
"\n"
"/* （可选）下拉展开时用向上三角 */\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/chevron-up.svg);\n"
"}\n"
"")
        self.comboBox_TesterLocation.setEditable(False)
        self.comboBox_TesterLocation.setObjectName("comboBox_TesterLocation")
        self.horizontalLayout_TesterLocation.addWidget(self.comboBox_TesterLocation)
        self.groupBox_Path = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_Path.setGeometry(QtCore.QRect(10, 120, 730, 110))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.groupBox_Path.setFont(font)
        self.groupBox_Path.setObjectName("groupBox_Path")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(parent=self.groupBox_Path)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(10, 20, 711, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.horizontalLayoutWidget_11.setFont(font)
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_InputPath = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_InputPath.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_InputPath.setObjectName("horizontalLayout_InputPath")
        self.label_InputPath = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_InputPath.sizePolicy().hasHeightForWidth())
        self.label_InputPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_InputPath.setFont(font)
        self.label_InputPath.setObjectName("label_InputPath")
        self.horizontalLayout_InputPath.addWidget(self.label_InputPath)
        spacerItem14 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_InputPath.addItem(spacerItem14)
        self.lineEdit_InputPath = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_InputPath.setFont(font)
        self.lineEdit_InputPath.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_InputPath.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_InputPath.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_InputPath.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_InputPath.setReadOnly(True)
        self.lineEdit_InputPath.setObjectName("lineEdit_InputPath")
        self.horizontalLayout_InputPath.addWidget(self.lineEdit_InputPath)
        self.pushButton_InputPath = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_InputPath.sizePolicy().hasHeightForWidth())
        self.pushButton_InputPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.pushButton_InputPath.setFont(font)
        self.pushButton_InputPath.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_InputPath.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_InputPath.setObjectName("pushButton_InputPath")
        self.horizontalLayout_InputPath.addWidget(self.pushButton_InputPath)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(parent=self.groupBox_Path)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 60, 711, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.horizontalLayoutWidget_12.setFont(font)
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_OutputPath = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_OutputPath.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_OutputPath.setObjectName("horizontalLayout_OutputPath")
        self.label_OutputPath = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.label_OutputPath.setFont(font)
        self.label_OutputPath.setObjectName("label_OutputPath")
        self.horizontalLayout_OutputPath.addWidget(self.label_OutputPath)
        spacerItem15 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_OutputPath.addItem(spacerItem15)
        self.lineEdit_OutputPath = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        self.lineEdit_OutputPath.setFont(font)
        self.lineEdit_OutputPath.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_OutputPath.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_OutputPath.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_OutputPath.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_OutputPath.setReadOnly(True)
        self.lineEdit_OutputPath.setObjectName("lineEdit_OutputPath")
        self.horizontalLayout_OutputPath.addWidget(self.lineEdit_OutputPath)
        self.pushButton_OutputPath = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.pushButton_OutputPath.setFont(font)
        self.pushButton_OutputPath.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_OutputPath.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_OutputPath.setObjectName("pushButton_OutputPath")
        self.horizontalLayout_OutputPath.addWidget(self.pushButton_OutputPath)
        self.groupBox_TestInformation = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_TestInformation.setGeometry(QtCore.QRect(10, 589, 950, 260))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.groupBox_TestInformation.setFont(font)
        self.groupBox_TestInformation.setStyleSheet("QWidget#groupBox_TestInformation {\n"
"    border: 2px solid #00A050;\n"
"}")
        self.groupBox_TestInformation.setObjectName("groupBox_TestInformation")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.groupBox_TestInformation)
        self.scrollArea.setGeometry(QtCore.QRect(5, 15, 941, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 939, 239))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_TestInformation = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_TestInformation.sizePolicy().hasHeightForWidth())
        self.tableWidget_TestInformation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        self.tableWidget_TestInformation.setFont(font)
        self.tableWidget_TestInformation.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.tableWidget_TestInformation.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.tableWidget_TestInformation.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tableWidget_TestInformation.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget_TestInformation.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget_TestInformation.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget_TestInformation.setTabKeyNavigation(False)
        self.tableWidget_TestInformation.setRowCount(14)
        self.tableWidget_TestInformation.setColumnCount(3)
        self.tableWidget_TestInformation.setObjectName("tableWidget_TestInformation")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_TestInformation.setItem(13, 1, item)
        self.tableWidget_TestInformation.horizontalHeader().setVisible(False)
        self.tableWidget_TestInformation.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_TestInformation.horizontalHeader().setHighlightSections(True)
        self.tableWidget_TestInformation.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_TestInformation.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_TestInformation.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_TestInformation.verticalHeader().setVisible(False)
        self.tableWidget_TestInformation.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_TestInformation.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_TestInformation.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.tableWidget_TestInformation)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_RunButton = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_RunButton.setGeometry(QtCore.QRect(750, 10, 211, 241))
        self.frame_RunButton.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_RunButton.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_RunButton.setObjectName("frame_RunButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame_RunButton)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 211, 231))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_RunAndVersion = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_RunAndVersion.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_RunAndVersion.setObjectName("verticalLayout_RunAndVersion")
        self.frame_7 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_Run = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_Run.setEnabled(True)
        self.pushButton_Run.setGeometry(QtCore.QRect(50, 0, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Run.sizePolicy().hasHeightForWidth())
        self.pushButton_Run.setSizePolicy(sizePolicy)
        self.pushButton_Run.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_Run.setMouseTracking(True)
        self.pushButton_Run.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.pushButton_Run.setStyleSheet("QPushButton#pushButton_Run {\n"
"  background-color: #00990C;     /* 背景色 */\n"
"  color: #FFFFFF;                /* 文本颜色 */\n"
"  border-style: solid;           \n"
"  border-width: 2px;\n"
"  border-color: #005F77;\n"
"  border-radius: 6px;           /* 圆角半径 */\n"
"  padding: 6px;                  /* 内边距，让内容不贴边 */\n"
"}\n"
"QPushButton#pushButton_Run:hover {\n"
"  background-color: #FF7A99;     /* 悬停效果 */\n"
"}\n"
"QPushButton#pushButton_Run:pressed {\n"
"  background-color: #005F77;     /* 按下效果 */\n"
"}")
        self.pushButton_Run.setAutoDefault(False)
        self.pushButton_Run.setDefault(False)
        self.pushButton_Run.setFlat(False)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.verticalLayout_RunAndVersion.addWidget(self.frame_7)
        spacerItem16 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_RunAndVersion.addItem(spacerItem16)
        self.frame_6 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame_6)
        self.progressBar.setGeometry(QtCore.QRect(5, 5, 201, 25))
        self.progressBar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_RunAndVersion.addWidget(self.frame_6)
        spacerItem17 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_RunAndVersion.addItem(spacerItem17)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_Version = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Version.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_Version.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_Version.setObjectName("horizontalLayout_Version")
        self.label_Version = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Version.sizePolicy().hasHeightForWidth())
        self.label_Version.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_Version.setFont(font)
        self.label_Version.setObjectName("label_Version")
        self.horizontalLayout_Version.addWidget(self.label_Version)
        spacerItem18 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Version.addItem(spacerItem18)
        self.lineEdit_Version = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.lineEdit_Version.setFont(font)
        self.lineEdit_Version.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineEdit_Version.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #4CAF50;   /* 绿色边框 */\n"
"    border-radius: 6px;          /* 圆角半径 */\n"
"    padding: 2px 6px;            /* 内边距，让文字不贴边 */\n"
"    background-color: #F0F0F0;   /* 背景颜色 */\n"
"}\n"
"")
        self.lineEdit_Version.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineEdit_Version.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_Version.setObjectName("lineEdit_Version")
        self.horizontalLayout_Version.addWidget(self.lineEdit_Version)
        self.verticalLayout.addLayout(self.horizontalLayout_Version)
        self.verticalLayout_RunAndVersion.addLayout(self.verticalLayout)
        self.verticalLayout_RunAndVersion.setStretch(0, 2)
        self.verticalLayout_RunAndVersion.setStretch(2, 1)
        self.verticalLayout_RunAndVersion.setStretch(4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar_BatteryAnalysis = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar_BatteryAnalysis.setObjectName("statusBar_BatteryAnalysis")
        MainWindow.setStatusBar(self.statusBar_BatteryAnalysis)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 970, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(parent=self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(parent=self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(parent=self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(parent=MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport_Report = QtGui.QAction(parent=MainWindow)
        self.actionExport_Report.setObjectName("actionExport_Report")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtGui.QAction(parent=MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(parent=MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtGui.QAction(parent=MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(parent=MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(parent=MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionPreferences = QtGui.QAction(parent=MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionShow_Toolbar = QtGui.QAction(parent=MainWindow)
        self.actionShow_Toolbar.setObjectName("actionShow_Toolbar")
        self.actionShow_Statusbar = QtGui.QAction(parent=MainWindow)
        self.actionShow_Statusbar.setObjectName("actionShow_Statusbar")
        self.actionZoom_In = QtGui.QAction(parent=MainWindow)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtGui.QAction(parent=MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionReset_Zoom = QtGui.QAction(parent=MainWindow)
        self.actionReset_Zoom.setObjectName("actionReset_Zoom")
        self.actionCalculate_Battery = QtGui.QAction(parent=MainWindow)
        self.actionCalculate_Battery.setObjectName("actionCalculate_Battery")
        self.actionAnalyze_Data = QtGui.QAction(parent=MainWindow)
        self.actionAnalyze_Data.setObjectName("actionAnalyze_Data")
        self.actionGenerate_Report = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_Report.setObjectName("actionGenerate_Report")
        self.actionBatch_Processing = QtGui.QAction(parent=MainWindow)
        self.actionBatch_Processing.setObjectName("actionBatch_Processing")
        self.actionUser_Mannual = QtGui.QAction(parent=MainWindow)
        self.actionUser_Mannual.setObjectName("actionUser_Mannual")
        self.actionOnline_Help = QtGui.QAction(parent=MainWindow)
        self.actionOnline_Help.setObjectName("actionOnline_Help")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionBatteryChartViewer = QtGui.QAction(parent=MainWindow)
        self.actionBatteryChartViewer.setObjectName("actionBatteryChartViewer")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Report)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuView.addAction(self.actionShow_Toolbar)
        self.menuView.addAction(self.actionShow_Statusbar)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView.addAction(self.actionReset_Zoom)
        self.menuTools.addAction(self.actionBatteryChartViewer)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCalculate_Battery)
        self.menuTools.addAction(self.actionAnalyze_Data)
        self.menuTools.addAction(self.actionGenerate_Report)
        self.menuTools.addAction(self.actionBatch_Processing)
        self.menuTools.addSeparator()
        self.menuHelp.addAction(self.actionUser_Mannual)
        self.menuHelp.addAction(self.actionOnline_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_BatteryType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_BatteryConfig.setTitle(_translate("MainWindow", "Battery Config"))
        self.label_Temperature.setText(_translate("MainWindow", "Temperature(℃)"))
        self.label_AcceleratedAging.setText(_translate("MainWindow", "Accelerated Aging(Years)"))
        self.label_Manufacturer.setText(_translate("MainWindow", "Manufacturer"))
        self.label_BatchDateCode.setText(_translate("MainWindow", "Batch/Date Code"))
        self.label_SamplesQty.setText(_translate("MainWindow", "Samples Qty"))
        self.label_BatteryType.setText(_translate("MainWindow", "Battery Type"))
        self.label_ConstructionMethod.setText(_translate("MainWindow", "Construction Method"))
        self.label_Specification.setText(_translate("MainWindow", "Specification"))
        self.label_RequiredUseableCapacity.setText(_translate("MainWindow", "Required Useable Capacity(mAh)"))
        self.label_CalculationNominalCapacity.setText(_translate("MainWindow", "Calculation Nominal Capacity(mAh)"))
        self.label_DatasheetNominalCapacity.setText(_translate("MainWindow", "Datasheet Nominal Capacity(mAh)"))
        self.groupBox_TestConfig.setTitle(_translate("MainWindow", "Test Config"))
        self.label_TestProfile.setText(_translate("MainWindow", "Test Profile"))
        self.pushButton_TestProfile.setText(_translate("MainWindow", "Open"))
        self.label_TestedBy.setText(_translate("MainWindow", "Tested By"))
        self.label_TesterLocation.setText(_translate("MainWindow", "Tester Location"))
        self.groupBox_Path.setTitle(_translate("MainWindow", "Path"))
        self.label_InputPath.setText(_translate("MainWindow", "Input Path "))
        self.pushButton_InputPath.setText(_translate("MainWindow", "Open"))
        self.label_OutputPath.setText(_translate("MainWindow", "Output Path"))
        self.pushButton_OutputPath.setText(_translate("MainWindow", "Open"))
        self.groupBox_TestInformation.setTitle(_translate("MainWindow", "Test Information"))
        __sortingEnabled = self.tableWidget_TestInformation.isSortingEnabled()
        self.tableWidget_TestInformation.setSortingEnabled(False)
        self.tableWidget_TestInformation.setSortingEnabled(__sortingEnabled)
        self.pushButton_Run.setText(_translate("MainWindow", "Run"))
        self.label_Version.setText(_translate("MainWindow", "Report Version"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionExport_Report.setText(_translate("MainWindow", "Export Report"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionShow_Toolbar.setText(_translate("MainWindow", "Show Toolbar"))
        self.actionShow_Statusbar.setText(_translate("MainWindow", "Show Statusbar"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionReset_Zoom.setText(_translate("MainWindow", "Reset Zoom"))
        self.actionCalculate_Battery.setText(_translate("MainWindow", "Calculate Battery"))
        self.actionAnalyze_Data.setText(_translate("MainWindow", "Analyze Data"))
        self.actionGenerate_Report.setText(_translate("MainWindow", "Generate Report"))
        self.actionBatch_Processing.setText(_translate("MainWindow", "Batch Processing"))
        self.actionUser_Mannual.setText(_translate("MainWindow", "User Mannual"))
        self.actionOnline_Help.setText(_translate("MainWindow", "Online Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionBatteryChartViewer.setText(_translate("MainWindow", "BatteryChartViewer"))
